name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [it, en]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: resume.${{ matrix.language }}.tex
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-${{ matrix.language }}.pdf
          path: resume-${{ matrix.language }}.pdf
